server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_gantt
    username: postgres
    password: 1007
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  mail:
    host: smtp.gmail.com
    port: 587
    username: cloudgantt77@gmail.com
    password: eketcrixnjrpvzwn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    confirmLinkIPAndPort: http://localhost:3000/confirm-email/




