package com.epam.cloudgantt.service;

import com.epam.cloudgantt.config.MessageByLang;
import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

@Service
public class MailServiceImpl implements MailService {

    private final JavaMailSender mailSender;

    private final static Logger LOGGER = LoggerFactory.getLogger(MailServiceImpl.class);
    @Value("${spring.mail.username}")
    String sender;

    public MailServiceImpl(JavaMailSender mailSender) {
        this.mailSender = mailSender;
    }

    @Async
    @Override
    public void send(String to, String subject, String message) {


        try {
            MimeMessage mimeMessage = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(mimeMessage, " charset=utf-8");
            helper.setTo(to);
            helper.setSubject(subject);
            helper.setFrom(sender);
            mimeMessage.setContent(message, "text/html; charset=utf-8");
            Thread thread = new Thread(() -> mailSender.send(mimeMessage));
            thread.start();
        } catch (MessagingException e) {
            LOGGER.error("failed to send email", e);
            throw new IllegalStateException("failed to send email");
        }
    }




    public String textForEmail(String confirmLink){
        String please_click_on_this_link_to_conform_your_email = "<!DOCTYPE html>\n" +
                "<html lang=\"en\">\n" +
                "<head>\n" +
                "    <meta charset=\"UTF-8\">\n" +
                "    <title>Title</title>\n" +
                "<style>\n" +
                "    .hero {\n" +
                "        background-color: #FAF8F1;\n" +
                "        color:#000;\n" +
                "        width:100%;\n" +
                "        padding:15px 20px;\n" +
                "        border-radius: 25px;\n" +
                "\n" +
                "    }\n" +
                "    .btn-secondary {\n" +
                "        background-color: #DD5353 !important;\n" +
                "        border:0;\n" +
                "        outline: none;\n" +
                "        border-radius: 25px;\n" +
                "        font-size:18px;\n" +
                "        font-weight: 400;\n" +
                "        padding:10px 20px !important;\n" +
                "        font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\";\n" +
                "\n" +
                "\n" +
                "    }\n" +
                "    .btn-secondary:hover, .btn-secondary:focus {\n" +
                "        outline: none !important;\n" +
                "        box-shadow: none !important;\n" +
                "    }\n" +
                "</style>\n" +
                "    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css\" integrity=\"sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO\" crossorigin=\"anonymous\">\n" +
                "</head>\n" +
                "<body>\n" +
                "\n" +
                "<div class=\"container p-5 mt-5\">\n" +
                "    <div class=\"hero\">\n" +
                "        <div class=\"px-4 py-5 my-5 text-center\">\n" +
                "            <h1 class=\"display-5 fw-bold\">Confirmation Request !</h1>\n" +
                "            <div class=\"col-lg-6 mx-auto\">\n" +
                "                <p class=\"lead mb-4\"> Welcome to CloudGantt!\n" +
                "\n" +
                "Please click Confirm button <br> <br> <br> \n" +
                "<div class=\"d-grid gap-2 d-sm-flex justify-content-sm-center\">\n" +
                "                    <button type=\"button\" class=\"btn btn-secondary btn-lg px-4 gap-3\"><a href=\"" + confirmLink + "\">Confirm</a></button>\n" +
                "                </div> <br>\n"+

                "Thank you for doing that,<br>\n" +

                "CloudGantt <br> <br> <br>\n" +

                "This is an autogenerated mail. Do not reply to this. </p>\n" +

                "            </div>\n" +
                "        </div>\n" +
                "    </div>\n" +
                "</div>\n" +
                "\n" +
                "</body>\n" +
                "</html>";
        return please_click_on_this_link_to_conform_your_email;
    }
}


